model_type: RNN
hyperparameters:
  lr: [0.0001, 0.000151, 0.000229, 0.000346, 0.000525, 0.000796, 0.001206, 0.001832, 0.002782, 0.004229, 0.006428, 0.009774, 0.014842, 0.022516, 0.034183, 0.051794, 0.078804, 0.11943, 0.18197, 0.27778]
  emb_size: [16, 32, 64, 128]
  hidden_size: [16, 32, 64, 128]
  dropout: [0.05, 0.1]
  depth: [1, 2, 3, 4, 5, 6]
  cell_type: ['LSTM']

