model_type: SAN
hyperparameters:
  lr: [0.00001, 0.000016, 0.000025, 0.00004, 0.000063, 0.0001, 0.000158, 0.000251, 0.000398, 0.000631, 0.001, 0.001585, 0.002512, 0.003981, 0.00631, 0.01, 0.01585, 0.02512, 0.03981, 0.0631]
  depth: [1, 2, 3, 4, 5, 6]
  d_model: [16, 32, 64, 128]
  dropout: [0.05, 0.1]
  heads: [2, 4, 8]
  d_ffn: [32, 64, 128]

num_samples: 300
total_cpus: 192
total_gpus: 0